FROM python:3.12-alpine

RUN apk add --no-cache gcc musl-dev python3-dev libffi-dev

RUN pip install --no-cache-dir pyrofork tgcrypto

WORKDIR /app

COPY . /app

ENV PYTHONUNBUFFERED=1

ENV SESSIONS_PATH=/app/sessions

CMD ["python", "main.py"]

